### ISSUE TITLE
💥 Add Your Quote ♥️

### ISSUE THREAD

**Issue by bauripalash** [bauripalash/quotebox#1]
### 💥 Note 💥: 
* Please Submit One Quote per User!
* Must Add Useful Pull Request Title (`updated that this` are bad practice)
* You have to add a comma (,) at the end of last quote if not present
* English Only
* No Spamming, Please!
* No Explicit , Sensitive Quotes!
* This Web App Was Created  for beginners as Starter for HacktoberFest!

### ⚠️ If someone does not fix Merge Conflicts within 2 Days from creation of the PR , those PRs will be marked as `Invalid` unless the PR Submitter asks for my help!
> Cause Hacktoberfest is all about contributing to Open Source but also Learning, and learning to fix Git Merge Conflict is an important topic!

Let's Do Something Cool 🔥🔥

**Comment by chilah** [comment]
I can do this

**Comment by molly7657** [comment]
@bauripalash happy to add a quote! :)

**Comment by whitek2** [comment]
Happy to contribute, this was a good first OSS experience!

**Comment by jaskarans2000** [comment]
added Winston Churchill's quote

**Comment by Kuljeet-123** [comment]
@bauripalash I'd like to add some qoute.!)

**Comment by Kuljeet-123** [comment]
@bauripalash please review my PR and merge into your repo and my PR id is #77 .

**Comment by darosadev** [comment]
@bauripalash I'll be happy to contribute with a quote 😄

**Comment by micaelalex** [comment]
Alan Watts Quote added: #140

**Comment by edwin-hightraffic** [comment]
Marie Forleo quote added: #142

**Comment by biswain2309** [comment]
Please review #186 Thank you!!

**Comment by ham118** [comment]
Please review #195 Thanks!

**Comment by dwil2444** [comment]
Please review PR #224 whenever you get the chance.

**Comment by jaywahr** [comment]
@bauripalash happy to add a quote! #232

**Comment by AzimPathan** [comment]
@bauripalash Please review PR #228  and add into your repo. Thanks!

**Comment by reybilla** [comment]
Added https://github.com/bauripalash/quotebox/pull/261

**Comment by ericabross** [comment]
@bauripalash I would love to make my first open-source contribution with this project. I have read the contribution guidelines, and I am ready to get started. Please let me know if you have any additional tips on how to proceed. Thanks for the opportunity!

**Comment by bauripalash** [comment]
@ericabross You can do so. But PR is not gonna get merged as large amount of PRs are already pending.
